import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import Responsivenav from './components/navigations/Responsivenav'


const poppins = Poppins({ 
  weight: ['400', '500','600','700','800'],
  subsets: ["latin"]
 });

export const metadata: Metadata = {
  title: "Agency|build your dreams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Responsivenav/>
        {children}</body>
    </html>
  );
}
